/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallasAsistencia;

/**
 *
 * @author Personal
 */
public class JFrameElegirTurno extends javax.swing.JFrame {

    /**
     * Creates new form JFrameElegirTurno
     */
    public JFrameElegirTurno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTurnoMañana = new javax.swing.JButton();
        btnTurnoTarde = new javax.swing.JButton();
        btnTurnoNoche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Elegir Horario de Clase");

        btnTurnoMañana.setBackground(new java.awt.Color(51, 255, 51));
        btnTurnoMañana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTurnoMañana.setText("Horario Mañana");
        btnTurnoMañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoMañanaActionPerformed(evt);
            }
        });

        btnTurnoTarde.setBackground(new java.awt.Color(255, 153, 0));
        btnTurnoTarde.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTurnoTarde.setText("Horario Tarde");
        btnTurnoTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoTardeActionPerformed(evt);
            }
        });

        btnTurnoNoche.setBackground(new java.awt.Color(0, 0, 153));
        btnTurnoNoche.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTurnoNoche.setForeground(new java.awt.Color(255, 255, 255));
        btnTurnoNoche.setText("Horario Noche");
        btnTurnoNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnoNocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTurnoMañana, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTurnoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTurnoNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnTurnoMañana, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTurnoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTurnoNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTurnoMañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoMañanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurnoMañanaActionPerformed

    private void btnTurnoTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoTardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurnoTardeActionPerformed

    private void btnTurnoNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnoNocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurnoNocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameElegirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameElegirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameElegirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameElegirTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameElegirTurno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTurnoMañana;
    private javax.swing.JButton btnTurnoNoche;
    private javax.swing.JButton btnTurnoTarde;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
